### ISSUE TITLE
check_free_space() always returns 0 during unattended installs (mac on LoginWindow)

### ISSUE THREAD

**Issue by joeschlimmer-ic** [grahampugh/erase-install#206]
**Describe the bug**
The _check_free_space()_ function always returns 0 during unattended installs (mac on LoginWindow). The osascsript dialogues are now set to run as the current user, and seems unable to get disk space without a user logged in. The function has no capability to fall back to some other method to check disk space.

I realize that with Apple Silcon / M1 macs on Big Sur/Monterey, user interaction / password entry is required for some parts of the startosinstall binary, so if this intended behavior going forward, my apologies.

Most of my fleet is Intel, and I have around 500 computers to erase-upgrade this summer. I am fine with forking and making modifications as needed, but I figured I'd send this report in just in case it wasn't intended.

**To Reproduce**
Setup a mac for upgrade. Leave it idle on Loginwindow
Create a Jamf Pro policy and scope it to the mac assigned for upgrade as needed.
Attach pkg _erase-install-depnotify-26.0.pkg_
Files and processes command. `/Library/Management/erase-install/erase-install.sh --os=12 --update --reinstall --depnotify --force-curl --cleanup-after-use`

I was also able to reproduce this with a manual pkg install over SSH, and a manually typed command to run the script, with the mac sitting on Loginwindow
 
**Expected behavior**
Check disk space function successfully detects disk space status from the loginwindow.

**Code/log output**
erase-install log shows that free disk space is 0 and ends the script.

**Environment:**
 - OS version [10.14, 10.15, 11, 12]
 - erase-install version [25.0 and 26.0]

**Comment by grahampugh** [comment]
I don't believe that `startosinstall` is designed to run at the login window, though it's not something I've tried as I did not design this script to run unattended.

Have you tried an older version of erase-install.sh, for example 0.22.0? That version used a more basic (less correct) way of calculating the free space. Does this work unattended?

**Comment by joeschlimmer-ic** [comment]
Yes, earlier versions (21 and 22) work unattended at the login screen. Interesting to know that that startosinstall may not be designed to run without a user signed in, I'll keep that in mind for the future.

If the design is moving towards features that require attention by the end user, I'll continue to use the older version until I can revamp my OS refresh workflow. (maybe move to in place upgrades with MDM software update commands or something.)

FWIW the new version works great from self service for users who need it.

Thanks for your hard work on this!

**Comment by grahampugh** [comment]
I added a fallback for drive space in to the v26 I just pushed. Give it a try.

**Comment by joeschlimmer-ic** [comment]
Awesome, I'll let you know how it turns out. 

Thanks.

**Comment by joeschlimmer-ic** [comment]
Hey, so the fallback doesn't seem to work after some jamf deployed and manual testing.

I believe this is because the test `if [[ ! "$free_disk_space" ]]; then` just does a true/false (or success/failure) test. If no one is logged in, `free_disk_space` still has a valid value, `0`. So no error or bool false, so the test does not catch it.

I added a second test to detect whether there is a ConsoleUser signed in, using the `$current_user"` variable set earlier in the script. This seemed to work as expected. If no one is signed into the UI, then $current_user has an empty value and `-z` catches it and runs the fallback disk space check command.

```bash
if [[ ! "$free_disk_space" ]] || [[ -z "$current_user" ]]; then
        # fall back to df -h if the above fails
        free_disk_space=$(df -Pk . | column -t | sed 1d | awk '{print $4}')
    fi
```
Is there a better way to do this?

**Comment by grahampugh** [comment]
Oh, yeah, I guess I was thinking python rather than bash. I guess just `[[ -z "$current_user" ]]` would be enough, actually.

**Comment by ehlersmj4814** [comment]
I am running this unattended, curling straight from github so I should be using the latest version. I am still seeing this in logs:
[check_free_space] ERROR - 0 GB free/purgeable disk space detected

Am I missing something?
Otherwise I am planning on using a jamf EA/smart group to get available disk space, then using --min-drive-space=00 to bypasss?

**Comment by grahampugh** [comment]
Unattended as in at the login window?

**Comment by ehlersmj4814** [comment]
Yes, this is being run at loginwindow by a jamf policy that is just curling from github.

**Comment by grahampugh** [comment]
I don't support unattended installs, though others have reported it to work. Can you try running the script manually on one of the affected devices and see if you get the same result?
